[package]
name = "groq"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json", "blocking"] }
llm_core = { path = "../llm_core" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
